<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function getTriCategory()
    {
        return $this->getEntityManager()

        ->createQuery(
            'SELECT p FROM AppBundle:Product p ORDER BY p.category ASC'
        )
        ->getResult();
    }

}
